name: Measure single data point

on:
  workflow_dispatch:
    inputs:
      case:
        description: "Case to measure"
        default: "common-libs"
        required: true
      scenario:
        description: "Scenario to measure"
        default: "development-build"
        required: true
      date:
        description: "Date to measure (yyyy-mm-dd)"
        default: "2021-10-01"
        required: true
jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.inputs.case }} ${{ github.event.inputs.scenario }} ${{ github.event.inputs.date }}
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ github.event.inputs.case }}-${{ github.event.inputs.date }}
          restore-keys: |
            yarn-${{ github.event.inputs.case }}-
            yarn-
      - uses: nick-invision/retry@v2.4.0
        with:
          max_attempts: 3
          timeout_minutes: 5
          command: yarn
      - uses: nick-invision/retry@v2.4.0
        with:
          max_attempts: 3
          timeout_minutes: 30
          command: node bin/measure-mean-normalized.js ${{ github.event.inputs.case }} ${{ github.event.inputs.scenario }} ${{ github.event.inputs.date }}
      - name: Setup git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: node bin/upload.js ${{ github.event.inputs.date }} ${{ secrets.GITHUB_TOKEN }}
