name: Measure random missing data point

on:
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch:
jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Yarn Cache Dir
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Yarn Cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-10000-${{ steps.missing.outputs.date }}
          restore-keys: |
            yarn-10000-
            yarn-
      - name: Yarn
        uses: nick-invision/retry@v2.4.0
        with:
          max_attempts: 3
          timeout_minutes: 5
          command: yarn
      - name: Measure
        uses: nick-invision/retry@v2.4.0
        with:
          max_attempts: 3
          timeout_minutes: 30
          command: node bin/measure-mean-normalized.js 10000 development-build+future-defaults
      - name: Measure
        uses: nick-invision/retry@v2.4.0
        with:
          max_attempts: 3
          timeout_minutes: 30
          command: node bin/measure-mean-normalized.js 10000 development-build+future-defaults+with-timeout-loader
      - name: Measure
        uses: nick-invision/retry@v2.4.0
        with:
          max_attempts: 3
          timeout_minutes: 30
          command: node bin/measure-mean-normalized.js 10000 development-build+future-defaults+with-multi-times
      - name: Measure
        uses: nick-invision/retry@v2.4.0
        with:
          max_attempts: 3
          timeout_minutes: 30
          command: node bin/measure-mean-normalized.js 10000 development-build+future-defaults+with-timeout-loader+with-multi-times
      - name: Setup git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Upload result
        run: node bin/upload.js ${{ secrets.GITHUB_TOKEN }}
