name: Scheduled Bench

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  bench:
    runs-on: [self-hosted, rspack-bench]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Init env
        uses: ./.github/actions/env
      - name: Build rspack
        run: node bin/build-rspack.js
      - name: Run benchmark
        run: node bin/bench.js
      - name: Setup git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Upload result
        run: node bin/upload.js ${{ secrets.GITHUB_TOKEN }}
